version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      
volumes:
  redis_data: