-- Tabela para consolidar todos os tipos de ganhos (freelas, salário, dividendos, mineração, etc.)
CREATE TABLE public.ganhos_gerais (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  dt_lcto text NULL,
  des_lcto text NULL,
  vlr_lcto text NULL,
  categoria_lcto text NULL,
  classe_lcto text NULL,
  CONSTRAINT ganhos_gerais_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Índices para performance
CREATE INDEX idx_ganhos_gerais_dt_lcto ON public.ganhos_gerais(dt_lcto);
CREATE INDEX idx_ganhos_gerais_categoria ON public.ganhos_gerais(categoria_lcto);
CREATE INDEX idx_ganhos_gerais_classe ON public.ganhos_gerais(classe_lcto);

-- RLS (Row Level Security) - ajuste conforme suas políticas
ALTER TABLE public.ganhos_gerais ENABLE ROW LEVEL SECURITY;

-- Política básica (permitir tudo para usuários autenticados)
CREATE POLICY "Enable all operations for authenticated users" ON public.ganhos_gerais
FOR ALL USING (auth.role() = 'authenticated');

-- Comentários
COMMENT ON TABLE public.ganhos_gerais IS 'Tabela consolidada para todos os tipos de ganhos mensais';
COMMENT ON COLUMN public.ganhos_gerais.dt_lcto IS 'Data do lançamento (formato texto YYYY-MM-DD)';
COMMENT ON COLUMN public.ganhos_gerais.des_lcto IS 'Descrição do lançamento';
COMMENT ON COLUMN public.ganhos_gerais.vlr_lcto IS 'Valor do lançamento (formato texto para compatibilidade)';
COMMENT ON COLUMN public.ganhos_gerais.categoria_lcto IS 'Categoria principal (Freelance, Salário, Dividendos, etc.)';
COMMENT ON COLUMN public.ganhos_gerais.classe_lcto IS 'Subcategoria ou classe específica';
